---
version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 10
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 10
...
