version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - zerologlint
  settings:
    revive:
      rules:
        - name: dot-imports
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
