---
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - stylecheck
    - tenv
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - zerologlint
linters-settings:
  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
