package router

const Collections = "collections"
const EmailAlertFrontend = "email-alert-frontend"
const Feedback = "feedback"
const FinderFrontend = "finder-frontend"
const Frontend = "frontend"
const GovernmentFrontend = "government-frontend"
const SmartAnswers = "smartanswers"

func schemaMap() (schema_map map[string]string) {
	schema_map = make(map[string]string)

	schema_map["answer"] = Frontend
	schema_map["completed_transaction"] = Feedback
	schema_map["consultation"] = GovernmentFrontend
	schema_map["contact"] = GovernmentFrontend
	schema_map["coronavirus_landing_page"] = Collections
	schema_map["corporate_information_page"] = GovernmentFrontend
	schema_map["detailed_guide"] = GovernmentFrontend
	schema_map["document_collection"] = GovernmentFrontend
	schema_map["email_alert_signup"] = EmailAlertFrontend
	schema_map["embassies_index"] = Collections
	schema_map["facet"] = ""
	schema_map["fatality_notice"] = Frontend
	schema_map["field_of_operation"] = GovernmentFrontend
	schema_map["fields_of_operation"] = Frontend
	schema_map["finder"] = FinderFrontend
	schema_map["finder_email_signup"] = FinderFrontend
	schema_map["generic"] = Collections
	schema_map["generic_with_external_related_links"] = ""
	schema_map["get_involved"] = Frontend
	schema_map["gone"] = Frontend
	schema_map["government"] = GovernmentFrontend
	schema_map["guide"] = GovernmentFrontend
	schema_map["help_page"] = Frontend
	schema_map["historic_appointment"] = Collections
	schema_map["historic_appointments"] = Collections
	schema_map["history"] = GovernmentFrontend
	schema_map["hmrc_manual"] = GovernmentFrontend
	schema_map["hmrc_manual_section"] = GovernmentFrontend
	schema_map["homepage"] = Frontend
	schema_map["how_government_works"] = GovernmentFrontend
	schema_map["html_publication"] = GovernmentFrontend
	schema_map["landing_page"] = Frontend
	schema_map["licence"] = ""
	schema_map["link_collection"] = ""
	schema_map["local_transaction"] = Frontend
	schema_map["mainstream_browse_page"] = Collections
	schema_map["manual"] = GovernmentFrontend
	schema_map["manual_section"] = GovernmentFrontend
	schema_map["ministers_index"] = Collections
	schema_map["need"] = "info-frontend"
	schema_map["news_article"] = Frontend
	schema_map["organisation"] = Collections
	schema_map["organisations_homepage"] = Collections
	schema_map["person"] = Collections
	schema_map["place"] = Frontend
	schema_map["publication"] = GovernmentFrontend
	schema_map["role"] = Collections
	schema_map["role_appointment"] = ""
	schema_map["service_manual_guide"] = GovernmentFrontend
	schema_map["service_manual_homepage"] = Frontend
	schema_map["service_manual_service_standard"] = GovernmentFrontend
	schema_map["service_manual_service_toolkit"] = Frontend
	schema_map["service_manual_topic"] = GovernmentFrontend
	schema_map["service_sign_in"] = GovernmentFrontend
	schema_map["simple_smart_answer"] = Frontend
	schema_map["smart_answer"] = SmartAnswers
	schema_map["specialist_document"] = Frontend
	schema_map["speech"] = Frontend
	schema_map["statistical_data_set"] = GovernmentFrontend
	schema_map["statistics_announcement"] = GovernmentFrontend
	schema_map["step_by_step_nav"] = Collections
	schema_map["take_part"] = Frontend
	schema_map["taxon"] = Collections
	schema_map["topical_event"] = Collections
	schema_map["topical_event_about_page"] = GovernmentFrontend
	schema_map["transaction"] = Frontend
	schema_map["travel_advice"] = Frontend
	schema_map["travel_advice_index"] = Frontend
	schema_map["working_group"] = GovernmentFrontend
	schema_map["world_index"] = Collections
	schema_map["world_location"] = ""
	schema_map["world_location_news"] = Collections
	schema_map["worldwide_corporate_information_page"] = GovernmentFrontend
	schema_map["worldwide_office"] = GovernmentFrontend
	schema_map["worldwide_organisation"] = GovernmentFrontend

	return
}
