#!/bin/sh

: ${DBNAME:=routerbench}

set -eu

cd "$(dirname "$0")"
cd ..

# Drop benchmark database
mongo localhost/"$DBNAME" --eval "db.dropDatabase()['ok']"

# Create test applications and routes
mongoimport --host localhost --db "$DBNAME" --collection applications --type json --file testdata/applications.json
mongoimport --host localhost --db "$DBNAME" --collection routes --type json --file testdata/routes.json
