name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
          cache: true

      - name: Setup MongoDB
        run: |
          make start_mongo

      - name: Build
        run: |
          make build

      - name: Run tests
        run: |
          make test
