name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
      - ".git**"
      - README.md
      - docs
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  test-go:
    name: Test Go
    uses: alphagov/govuk-infrastructure/.github/workflows/go-test.yml@7f2539d31e77d1bcec1ebc6fc7796f086e65a5af # main
    permissions:
      packages: write
      pull-requests: write

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - run: |
          make lint

  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@7f2539d31e77d1bcec1ebc6fc7796f086e65a5af # main
    permissions:
      security-events: write
